added reset ramp to CancelAll command
FRC4048/FRC2024_Java pull request #125
Opened 2024-03-02 21:14 UTC by Levercpu

2024-03-02 23:36 UTC, batchen1 requested changes

2024-03-02 23:36 UTC, batchen1 commented on src/main/java/frc/robot/commands/CancelAll.java
> +  Amp amp;
remove this

2024-03-03 00:16 UTC, neo-Aditya requested changes

2024-03-03 00:16 UTC, neo-Aditya commented on src/main/java/frc/robot/commands/CancelAll.java
> +    new RetractAmp(amp);
That's not going to do what you think it'll do

2024-03-03 00:16 UTC, neo-Aditya commented on src/main/java/frc/robot/commands/sequences/CancelAllSequence.java
> +            new WaitCommand(0.5),
Do you want to put this in Constants?

2024-03-03 02:50 UTC, bengold22 requested changes

2024-03-03 02:50 UTC, bengold22 commented on src/main/java/frc/robot/commands/sequences/CancelAllSequence.java
> +            new WaitCommand(0.5),
Remove this WaitCommand, do not leave it here and add the value to constants.

2024-03-03 21:28 UTC, neo-Aditya requested changes

2024-03-03 21:28 UTC, neo-Aditya commented on src/main/java/frc/robot/commands/sequences/CancelAllSequence.java
You may want to make it so that it'll stop the drivetrain aswell.

2024-03-03 23:38 UTC, batchen1 approved these changes

2024-03-03 23:45 UTC, batchen1 approved these changes

2024-03-03 23:48 UTC, merged