Climber subsystem
FRC4048/FRC2024_Java pull request #16
Opened 2024-01-28 19:27 UTC by Levercpu

We set up some code that allows for the robot to automtically climb and balance based on the pitch of the navx gyro #best.

2024-01-28 20:52 UTC, bengold22 requested changes

2024-01-28 20:52 UTC, bengold22 commented on src/main/java/frc/robot/Constants.java
> +    public static final double ArmSeperationDistance = 5.00;
Why does your PR have INTAKE constants? Please remove any constant not related to the code in this PR.

2024-01-28 20:52 UTC, bengold22 commented on src/main/java/frc/robot/commands/StaticClimb.java
> +        System.out.println("Im Climbing");
Remove the System.out.println

2024-01-28 20:52 UTC, bengold22 commented on src/main/java/frc/robot/commands/StaticClimb.java
> +        if (Timer.getFPGATimestamp()-startTime>10) {
Move 10 to constants (something like CLIMB_TIMEOUT_S)

2024-01-28 20:52 UTC, bengold22 commented on src/main/java/frc/robot/commands/StaticClimb.java
> +        if (Timer.getFPGATimestamp()-startTime>10) {
Also lets reduce it now to 4

2024-01-28 20:52 UTC, bengold22 commented on src/main/java/frc/robot/commands/StaticClimb.java
> +            climber.raise(false);
I think this is supposed to be true, not false

2024-01-28 20:52 UTC, bengold22 commented on src/main/java/frc/robot/subsystems/Intake.java
Please delete this file, it looks to me like this was experimental code (it's using PWM)

2024-01-28 20:52 UTC, bengold22 commented on src/main/java/frc/robot/subsystems/Outtake.java
Delete this file, same an Intake.java

2024-01-28 20:52 UTC, bengold22 commented on src/main/java/frc/robot/utils/IntakeState.java
Delete this file

2024-01-28 20:52 UTC, bengold22 commented on src/main/java/frc/robot/utils/OuttakeState.java
Delete this file

2024-02-08 19:46 UTC, goatfanboi23 commented on src/main/java/frc/robot/RobotContainer.java
> +  private Climber climber = null;
there is no need to initialize climber to null. Consider removing the null and making Climber final.

2024-02-08 19:47 UTC, noahheller commented on src/main/java/frc/robot/RobotContainer.java
> +    SmartShuffleboard.putCommand("TEST","WheelAlign",new WheelAlign(drivetrain));
Should be in wrapped in an if(CLIMBER_DEBUG)

2024-02-08 19:48 UTC, goatfanboi23 commented on src/main/java/frc/robot/subsystems/Climber.java
> +        SmartShuffleboard.put("Climber", "Climber State", "Pitch", getGyroPitch());
another If debug

2024-02-08 19:49 UTC, goatfanboi23 commented on src/main/java/frc/robot/Constants.java
> +    public static final double ArmSeperationDistance = 5.00;
Should be all CAPS to follow convention

2024-02-11 18:23 UTC, bengold22 approved these changes

2024-02-11 18:30 UTC, merged