Nh color stip
FRC4048/FRC2024_Java pull request #164
Opened 2024-03-17 14:42 UTC by goatfanboi23

2024-03-21 01:48 UTC, goatfanboi23 commented on src/main/java/frc/robot/commands/SetLEDValue.java
this is Ben's code left over from branch split

2024-03-22 23:31 UTC, batchen1 requested changes

2024-03-22 23:31 UTC, batchen1 commented on src/main/java/frc/robot/constants/GameConstants.java
> +    public static final boolean VISION_DEBUG = true;
false

2024-03-22 23:31 UTC, batchen1 commented on src/main/java/frc/robot/Robot.java
> +        robotContainer.getLEDStrip().setPatternLater(2,BlinkinPattern.DARK_GRAY);
Is this the right name?

2024-03-22 23:55 UTC, batchen1 approved these changes

2024-03-23 22:20 UTC, merged