staggered the slower shooter motor by 0.1 seconds to reduced peak cur…
FRC4048/FRC2024_Java pull request #171
Opened 2024-03-20 22:39 UTC by Levercpu

…rent

2024-03-21 12:11 UTC, Levercpu commented
Don't review this yet I'm still testing, I'm sorry that i made the pull request too early.

2024-03-23 21:01 UTC, armadilloz requested changes
Also do the same for `BasicShoot`

2024-03-23 21:01 UTC, armadilloz commented on src/main/java/frc/robot/commands/shooter/AdvancedSpinningShot.java
> +        if (!leftStarted) {
Need to calculate the speeds first and then start the faster motor first.

2024-03-23 21:01 UTC, armadilloz commented on src/main/java/frc/robot/commands/shooter/AdvancedSpinningShot.java
> +            shooter.setShooterMotorLeftRPM(shooterSpeed.getLeftMotorSpeed());
No need for booleans - the PID sets need to be set on every cycle (or else the watchdog may trip - this is normally more relevant for the set(power) command). Just set the PID values for the early motor always, and then set the PID for the late motor once the timer elapses.

2024-03-23 21:01 UTC, armadilloz commented on src/main/java/frc/robot/commands/shooter/AdvancedSpinningShot.java
> +        return alignable == null || alignableSupplier.get() == null || !alignable.equals(alignableSupplier.get()); // IDK WHAT THIS DOES
No need for the comment - you can ask @goatfanboi23 to document the method.

2024-03-23 21:01 UTC, armadilloz commented on src/main/java/frc/robot/commands/shooter/SetShooterSpeed.java
> +  private Timer timer;
This command is only used from shuffleboard. Can be used for testing...

2024-03-23 21:01 UTC, armadilloz commented on src/main/java/frc/robot/commands/shooter/ShootAmp.java
>  public class ShootAmp extends Command {
This command is never used.

2024-03-23 21:01 UTC, armadilloz commented on src/main/java/frc/robot/commands/shooter/ShootSpeaker.java
> +
Remove whitespace changes.

2024-03-23 21:01 UTC, armadilloz commented on src/main/java/frc/robot/commands/shooter/ShootSpeaker.java
> +            if (!leftStarted) {
Same comments as in `AdvancedSpinningShot`: No need for booleans, always set the values

2024-03-23 21:01 UTC, armadilloz commented on src/main/java/frc/robot/constants/ConstantsTestbed.java
> +    public static final int SHOOTER_MOTOR_LEFT = 45;
Why did you reverse the motors?

2024-03-23 21:01 UTC, armadilloz commented on src/main/java/frc/robot/constants/GameConstants.java
> +    public static final double SHOOTER_MOTOR_STARTUP_OFFSET = 0.2; //TODO: Refine This Number
Remove the comment

2024-03-23 21:01 UTC, armadilloz commented on src/main/java/frc/robot/subsystems/Shooter.java
> +    //neoPidMotorLeft.getNeoMotor().setSmartCurrentLimit(10);
Remove the commented put code.

2024-03-23 21:01 UTC, armadilloz commented on src/main/java/frc/robot/subsystems/Shooter.java
> +    leftCurrent = neoPidMotorLeft.getNeoMotor().getOutputCurrent();
Move this into the `SHOOTER_DEBUG` section

2024-03-23 21:05 UTC, armadilloz commented on src/main/java/frc/robot/commands/shooter/ShootSpeaker.java
> +
This command's `isFinished` should be changed - your command will not properly run right now because it will end before the timer elapses.

2024-03-24 19:38 UTC, armadilloz commented on src/main/java/frc/robot/commands/pathplanning/BasicShoot.java
> +        }
isFinished will terminate the command potentially before the second motor kicks in.

2024-03-24 19:39 UTC, armadilloz commented on src/main/java/frc/robot/commands/shooter/ShootAmp.java
>  public class ShootAmp extends Command {
Undo changes fo this class.

2024-03-24 19:40 UTC, armadilloz commented on src/main/java/frc/robot/commands/shooter/ShootSpeaker.java
> +        return Timer.getFPGATimestamp()-startTime>5.1;
what is 5.1?

2024-03-24 20:56 UTC, armadilloz approved these changes

2024-03-24 20:56 UTC, merged