move game piece
FRC4048/FRC2024_Java pull request #188
Opened 2024-03-26 22:34 UTC by goatfanboi23

2024-03-26 22:41 UTC, batchen1 requested changes

2024-03-26 22:41 UTC, batchen1 commented on src/main/java/frc/robot/commands/MoveToGamepiece.java
> +            if (pieceNotSeenCounter >= Constants.LIMELIGHT_PIECE_NOT_SEEN_COUNT){
This is not needed

2024-03-27 02:49 UTC, goatfanboi23 commented on src/main/java/frc/robot/commands/MoveToGamepiece.java
> +            if (pieceNotSeenCounter >= Constants.LIMELIGHT_PIECE_NOT_SEEN_COUNT){
done

2024-03-27 13:16 UTC, batchen1 requested changes

2024-03-27 13:16 UTC, batchen1 commented on src/main/java/frc/robot/constants/GameConstants.java
> +    public static final boolean SWERVE_DEBUG = true;
false

2024-03-27 22:11 UTC, batchen1 approved these changes

2024-03-27 22:11 UTC, merged