LV logging
FRC4048/FRC2024_Java pull request #59
Opened 2024-02-19 18:41 UTC by WidestDiamond90

Added logging to shuffleboard commands

2024-02-19 21:45 UTC, bengold22 requested changes

2024-02-19 21:45 UTC, bengold22 commented on src/main/java/frc/robot/constants/GameConstants.java
> +    public static final boolean SHOOTER_DEBUG = true;
Now that you've confirmed logging is working, you should not flip these to true in your PR.

2024-02-23 00:51 UTC, neo-Aditya requested changes

2024-02-23 00:51 UTC, neo-Aditya commented on src/main/java/frc/robot/constants/GameConstants.java
> +    public static final boolean ENABLE_LOGGING = true;
Please keep this false

2024-02-24 00:30 UTC, neo-Aditya submitted a review, later dismissed

2024-02-24 00:30 UTC, neo-Aditya commented on src/main/java/frc/robot/RobotContainer.java
> +        autoChooser.addOnValidationCommand(()->CommandUtil.logged(new SetInitOdom(drivetrain,autoChooser)));
Are you setting the name in the commands aswell?

2024-02-24 21:17 UTC, batchen1 requested changes

2024-02-24 21:17 UTC, batchen1 commented on src/main/java/frc/robot/RobotContainer.java
> +        drivetrain.setDefaultCommand(CommandUtil.logged(new Drive(drivetrain, joyleft::getY, joyleft::getX, joyright::getX)));
We don't want to log the default commands because they clutter the log because the log in every cycle.

2024-02-24 21:17 UTC, batchen1 commented on src/main/java/frc/robot/constants/GameConstants.java
> -    public static final double MAX_CLIMBER_ENCODER = 80.0;
This was probably deleted accidentally. Add this back.

2024-02-24 22:04 UTC, batchen1 approved these changes

2024-02-24 23:31 UTC, batchen1 approved these changes

2024-02-24 23:42 UTC, bengold22 approved these changes

2024-02-24 23:44 UTC, bengold22 approved these changes

2024-02-24 23:44 UTC, merged